### ISSUE TITLE
2021

### ISSUE THREAD

**Issue by JavaGuySoho** [JavaGuySoho/OpenVINO#1]
cd C:\Program Files (x86)\Intel\openvino_2021\bin
setupvars.bat

cd C:\Program Files (x86)\Intel\openvino_2021\deployment_tools\model_optimizer\install_prerequisites
install_prerequisites.bat

**Comment by JavaGuySoho** [comment]
-------------------------------------------------------------
  WARNING: The scripts backend-test-tools.exe, check-model.exe and check-node.exe are installed in 'C:\Users\百晓生看世界\AppData\Roaming\Python\Python36\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
-------------------------------------------------------------

**Comment by JavaGuySoho** [comment]
cd C:\Program Files (x86)\Intel\openvino_2021.2.185\deployment_tools\demo
demo_squeezenet_download_convert_run.bat

**Comment by JavaGuySoho** [comment]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Intel\openvino_2021.2.185\deployment_tools\open_model_zoo\tools\downloader\downloader.py", line 84, in try_download
    chunk_iterable, continue_offset = start_download(offset=progress.size)
  File "C:\Program Files (x86)\Intel\openvino_2021.2.185\deployment_tools\open_model_zoo\tools\downloader\common.py", line 332, in start_download
    headers=self.http_range_headers(offset))
  File "C:\Users\百晓生看世界\AppData\Roaming\Python\Python36\site-packages\requests\sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\百晓生看世界\AppData\Roaming\Python\Python36\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\百晓生看世界\AppData\Roaming\Python\Python36\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\百晓生看世界\AppData\Roaming\Python\Python36\site-packages\requests\adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /forresti/SqueezeNet/a47b6f13d30985279789d08053d37013d67d131b/SqueezeNet_v1.1/deploy.prototxt (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')",),))
########## Error: Download failed

FAILED:
squeezenet1.1
squeezenet1.1 model downloading completed

**Comment by JavaGuySoho** [comment]
cd C:\Program Files (x86)\Intel\openvino_2021\deployment_tools\model_optimizer\install_prerequisites

install_prerequisites_caffe.bat
install_prerequisites_tf2.bat
install_prerequisites_mxnet.bat
install_prerequisites_onnx.bat
install_prerequisites_kaldi.bat

**Comment by JavaGuySoho** [comment]
pip install -i https://pypi.tuna.tsinghua.edu.cn/simple tensorflow==2.4.0

**Comment by JavaGuySoho** [comment]
Creating Visual Studio 15 2017 x64 files in C:\Users\百晓生看世界\Documents\Intel\OpenVINO\inference_engine_samples_build...
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.19042.
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:7 (project):
  No CMAKE_C_COMPILER could be found.

**Comment by JavaGuySoho** [comment]
C:\Users\百晓生看世界\AppData\Roaming\fypdfr

**Comment by JavaGuySoho** [comment]
C:\Users\百晓生看世界\AppData\Roaming\FileAssistor\FileAssistor
